version: '3.4'

services:
  tiendaservices.api.autor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    ports:
      - "5000:80"

  tiendaservices.api.libro:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"


  tiendaservices.api.carritocompra:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__LibrosAPI=http://tiendaservices.api.libro
    ports:
      - "5002:80"


  tiendaservices.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__AutoresAPI=http://tiendaservices.api.gateway
    depends_on:
      - tiendaservices.api.libro
    ports:
      - "5003:80"

